#!/usr/bin/env bash

ESC='\033['
RED="${ESC}0;31m"
GREEN="${ESC}0;32m"
YELLOW="${ESC}1;33m"
BLUE="${ESC}0;34m"
CYAN="${ESC}0;36m"
RESET="${ESC}0m"

function red() {
    printf "${RED}$@${RESET}"
}

function green() {
    printf "${GREEN}$@${RESET}"
}

function yellow() {
    printf "${YELLOW}$@${RESET}"
}

function cyan() {
    printf "${CYAN}$@${RESET}"
}

function blue() {
    printf "${BLUE}$@${RESET}"
}

sed "s/ Running / $(green 'Running') /" |
    sed "s/ ImagePullBackOff / $(red 'ImagePullBackOff') /" |
    sed "s/ CrashLoopBackOff / $(red 'CrashLoopBackOff') /" |
    sed "s/ Evicted / $(red 'Evicted') /" |
    sed "s/ Completed / $(blue 'Completed') /" |
    sed "s/ Terminating / $(cyan 'Terminating') /" |
    sed "s/ Pending / $(cyan 'Pending') /"
